# infura project id
INFURA_PROJECT_ID: 4dd245ab4e1e4529acbcd3b5a81d02d4

# mainnet
INFURA_MAINNET_HTTPS_URL: https://mainnet.infura.io/v3/
INFURA_MAINNET_WSS_URL: wss://mainnet.infura.io/ws/v3/

TOKEN_ADDRESS: "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0"

MAIN_WALLET: "0x13f4EA83D0bd40E75C8222255bc855a974568Dd4"

WHITE_LIST: []
