# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/layouts/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 341)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setStyleSheet("background: white;\n"
"border-radius: 5px;\n"
"border: 2px solid black;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.qline_project_id = QtWidgets.QLineEdit(self.groupBox)
        self.qline_project_id.setStyleSheet("background: white;\n"
"border-radius: 5px;\n"
"border: 2px solid black;")
        self.qline_project_id.setPlaceholderText("")
        self.qline_project_id.setObjectName("qline_project_id")
        self.gridLayout_2.addWidget(self.qline_project_id, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet("background: white;\n"
"border-radius: 5px;\n"
"border: 2px solid black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.qline_token = QtWidgets.QLineEdit(self.groupBox)
        self.qline_token.setStyleSheet("background: white;\n"
"border-radius: 5px;\n"
"border: 2px solid black;")
        self.qline_token.setPlaceholderText("")
        self.qline_token.setObjectName("qline_token")
        self.gridLayout_2.addWidget(self.qline_token, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setStyleSheet("background: white;\n"
"border-radius: 5px;\n"
"border: 2px solid black;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.qline_main_wallet = QtWidgets.QLineEdit(self.groupBox)
        self.qline_main_wallet.setStyleSheet("background: white;\n"
"border-radius: 5px;\n"
"border: 2px solid black;")
        self.qline_main_wallet.setPlaceholderText("")
        self.qline_main_wallet.setObjectName("qline_main_wallet")
        self.gridLayout_2.addWidget(self.qline_main_wallet, 2, 1, 1, 1)
        self.btn_start = QtWidgets.QPushButton(self.groupBox)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout_2.addWidget(self.btn_start, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_3.setText(_translate("MainWindow", "INFURA PROJECT ID"))
        self.qline_project_id.setText(_translate("MainWindow", "4dd245ab4e1e4529acbcd3b5a81d02d4"))
        self.label.setText(_translate("MainWindow", "Token"))
        self.qline_token.setText(_translate("MainWindow", "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"))
        self.label_2.setText(_translate("MainWindow", "Main Wallet"))
        self.qline_main_wallet.setText(_translate("MainWindow", "0x13f4EA83D0bd40E75C8222255bc855a974568Dd4"))
        self.btn_start.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
